title: SmallSuggestions — Free Online Tools for JSON, CSV, XML & Excel Conversion
description: Convert, format, and manage your data easily with SmallSuggestions. Free browser-based tools for JSON, CSV, XML, and Excel — secure, accurate, and fast.
permalink: ':title'
baseurl: ""
url: "https://smallsugesstions.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here
image: 
# Author Settings
author: SmallSuggestions # add your name
author-img: smallsugesstions.webp # add your photo
about-author: Explore The Right Productivity Tools For JSON, XML, CSV And Excel to Skyrocket Your Workflow # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: sharpedge74-cmyk # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: sohail-anwar # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
kramdown:
  input: Kramdown
  
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-toc
  - jekyll-livereload
  - jekyll-redirect-from
toc:
  min_level: 2  # Adjust if you want to skip h1
  max_level: 6
  list_class: toc
  list_class: toc__list
  sublist_class: toc__sublist


exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
